# Generated by Django 3.2.5 on 2022-01-31 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='The name of the club must contain at least three characters!', regex='^.{3,}$')])),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'club',
                'verbose_name_plural': 'clubs',
                'abstract': False,
            },
        ),
    ]
