# Generated by Django 3.2.5 on 2022-02-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='club',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('A', 'Applicant'), ('M', 'Member'), ('O', 'Officer'), ('CO', 'Owner')], default='A', max_length=2),
        ),
    ]
