# Generated by Django 3.2.5 on 2022-03-30 14:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genres_preferences',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Adult Fiction', 'Adult Fiction'), ('Adventure', 'Adventure'), ('Animals', 'Animals'), ('Art', 'Art'), ('Autobiography', 'Autobiography'), ('Biography', 'Biography'), ('Business', 'Business'), ('Childrens', 'Childrens'), ('Christian', 'Christian'), ('Christian Fiction', 'Christian Fiction'), ('Classics', 'Classics'), ('Crime', 'Crime'), ('Cultural', 'Cultural'), ('European Literature', 'European Literature'), ('Fantasy', 'Fantasy'), ('Feminism', 'Feminism'), ('Fiction', 'Fiction'), ('Food and Drink', 'Food and Drink'), ('Health', 'Health'), ('Historical', 'Historical'), ('History', 'History'), ('Holiday', 'Holiday'), ('Horror', 'Horror'), ('Humor', 'Humor'), ('Language', 'Language'), ('Law', 'Law'), ('Media Tie In', 'Media Tie In'), ('Mystery', 'Mystery'), ('Nonfiction', 'Nonfiction'), ('Paranormal', 'Paranormal'), ('Parenting', 'Parenting'), ('Philosophy', 'Philosophy'), ('Plays', 'Plays'), ('Poetry', 'Poetry'), ('Politics', 'Politics'), ('Psychology', 'Psychology'), ('Realistic Fiction', 'Realistic Fiction'), ('Reference', 'Reference'), ('Relationships', 'Relationships'), ('Religion', 'Religion'), ('Romance', 'Romance'), ('Science', 'Science'), ('Science Fiction', 'Science Fiction'), ('Self Help', 'Self Help'), ('Sequential Art', 'Sequential Art'), ('Short Stories', 'Short Stories'), ('Spirituality', 'Spirituality'), ('Sports', 'Sports'), ('Thriller', 'Thriller'), ('Travel', 'Travel'), ('Westerns', 'Westerns'), ('Womens Fiction', 'Womens Fiction'), ('Writing', 'Writing'), ('Young Adult', 'Young Adult')], max_length=549),
        ),
    ]
