# Generated by Django 3.2.5 on 2022-03-20 12:38

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20220301_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genres_preferences',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Fiction', 'Fiction'), ('Food and Drink', 'Food and Drink'), ('Science Fiction', 'Science Fiction'), ('Classics', 'Classics'), ('Nonfiction', 'Nonfiction'), ('Horror', 'Horror'), ('Mystery', 'Mystery'), ('Philosophy', 'Philosophy'), ('Business', 'Business'), ('Historical', 'Historical'), ('Romance', 'Romance'), ('Crime', 'Crime'), ('Womens Fiction', 'Womens Fiction'), ('Fantasy', 'Fantasy'), ('Young Adult', 'Young Adult'), ('Sequential Art', 'Sequential Art'), ('Politics', 'Politics'), ('Childrens', 'Childrens'), ('History', 'History'), ('Self Help', 'Self Help'), ('Humor', 'Humor'), ('Thriller', 'Thriller'), ('Autobiography', 'Autobiography'), ('Poetry', 'Poetry'), ('Short Stories', 'Short Stories'), ('Language', 'Language'), ('Science', 'Science'), ('Travel', 'Travel'), ('Parenting', 'Parenting'), ('Paranormal', 'Paranormal'), ('Biography', 'Biography'), ('Christian', 'Christian'), ('European Literature', 'European Literature'), ('Psychology', 'Psychology'), ('Adventure', 'Adventure'), ('Religion', 'Religion'), ('Holiday', 'Holiday'), ('Animals', 'Animals'), ('Christian Fiction', 'Christian Fiction'), ('Reference', 'Reference'), ('Spirituality', 'Spirituality'), ('Feminism', 'Feminism'), ('Health', 'Health'), ('Cultural', 'Cultural'), ('Adult Fiction', 'Adult Fiction'), ('Writing', 'Writing'), ('Realistic Fiction', 'Realistic Fiction'), ('Law', 'Law'), ('Art', 'Art'), ('Plays', 'Plays'), ('Relationships', 'Relationships'), ('Westerns', 'Westerns'), ('Sports', 'Sports')], max_length=536, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('R', 'Reject'), ('A', 'Accept')], default='P', max_length=1),
        ),
    ]
