# Generated by Django 3.2.5 on 2022-02-01 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('isbn', models.CharField(max_length=17)),
                ('genre', models.CharField(choices=[('horror', 'Horror'), ('fantasy', 'Fantasy'), ('poetry', 'Poetry'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('graphic_novel', 'Graphic novel'), ('anthology', 'Anthology'), ('fairy_tale', 'Fairy tale')], max_length=20)),
                ('isFranchise', models.BooleanField(default=False)),
            ],
        ),
    ]
