# Generated by Django 3.2.5 on 2022-02-17 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20220217_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_book', to='clubs.book'),
        ),
    ]
