# Generated by Django 3.2.5 on 2022-02-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_auto_20220225_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('R', 'Reject'), ('P', 'Pending'), ('A', 'Accept')], default='P', max_length=1),
        ),
    ]
