# Generated by Django 3.2.5 on 2022-02-25 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_alter_invitation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='club_book', to='clubs.book'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('R', 'Reject'), ('A', 'Accept')], default='P', max_length=1),
        ),
    ]
