# Generated by Django 3.2.5 on 2022-04-01 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_auto_20220331_2106'),
        ('clubs', '0006_alter_invitation_status'),
    ]

    operations = [
    ]
