# Generated by Django 3.2.5 on 2022-03-30 10:21

import clubs.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20220314_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='deadline',
            field=models.DateField(default=datetime.date.today, validators=[clubs.validators.validate_date], verbose_name='Sign Up Deadline (YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('R', 'Reject'), ('A', 'Accept'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
