# Generated by Django 3.2.5 on 2022-02-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20220225_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='club_book',
            new_name='clubs_book',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('A', 'Accept'), ('R', 'Reject'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
