# Generated by Django 3.2.5 on 2022-03-30 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_user_managers'),
        ('clubs', '0008_alter_invitation_status'),
    ]

    operations = [
    ]
