# Generated by Django 3.2.5 on 2022-02-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_auto_20220203_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
