# Generated by Django 3.2.5 on 2022-04-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_auto_20220401_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('R', 'Reject'), ('A', 'Accept')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=20),
        ),
    ]
