# Generated by Django 3.2.5 on 2022-03-04 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_alter_invitation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpost',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='description',
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.event'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('R', 'Reject'), ('A', 'Accept'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
