# Generated by Django 3.2.5 on 2022-02-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0012_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={},
        ),
    ]
