# Generated by Django 3.2.5 on 2022-03-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_auto_20220307_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('A', 'Accept'), ('R', 'Reject'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
