# Generated by Django 3.2.5 on 2022-03-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_alter_invitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='join',
            field=models.BooleanField(default=True),
        ),
    ]
