# Generated by Django 3.2.5 on 2022-03-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_alter_invitation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('R', 'Reject'), ('P', 'Pending'), ('A', 'Accept')], default='P', max_length=1),
        ),
    ]
