# Options for available genres
def get_genres():
    genre_choices = [
        ('Fiction','Fiction'),
        ('Food and Drink','Food and Drink'),
        ('Science Fiction','Science Fiction'),
        ('Classics','Classics'),
        ('Nonfiction','Nonfiction'),
        ('Horror','Horror'),
        ('Mystery','Mystery'),
        ('Philosophy','Philosophy'),
        ('Business','Business'),
        ('Historical','Historical'),
        ('Romance','Romance'),
        ('Crime','Crime'),
        ('Womens Fiction','Womens Fiction'),
        ('Fantasy','Fantasy'),
        ('Young Adult','Young Adult'),
        ('Sequential Art','Sequential Art'),
        ('Politics','Politics'),
        ('Childrens','Childrens'),
        ('History','History'),
        ('Self Help','Self Help'),
        ('Humor','Humor'),
        ('Thriller','Thriller'),
        ('Autobiography','Autobiography'),
        ('Poetry','Poetry'),
        ('Short Stories','Short Stories'),
        ('Language','Language'),
        ('Science','Science'),
        ('Travel','Travel'),
        ('Parenting','Parenting'),
        ('Paranormal','Paranormal'),
        ('Biography','Biography'),
        ('Christian','Christian'),
        ('European Literature','European Literature'),
        ('Psychology','Psychology'),
        ('Adventure','Adventure'),
        ('Religion','Religion'),
        ('Holiday','Holiday'),
        ('Animals','Animals'),
        ('Christian Fiction','Christian Fiction'),
        ('Reference','Reference'),
        ('Spirituality','Spirituality'),
        ('Feminism','Feminism'),
        ('Health','Health'),
        ('Cultural','Cultural'),
        ('Adult Fiction','Adult Fiction'),
        ('Writing','Writing'),
        ('Realistic Fiction','Realistic Fiction'),
        ('Law','Law'),
        ('Art','Art'),
        ('Plays','Plays'),
        ('Relationships','Relationships'),
        ('Westerns','Westerns'),
        ('Sports','Sports')
    ]

    return genre_choices
